<?php

namespace AppBundle\Repository;

/**
 * CoupleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoupleRepository extends \Doctrine\ORM\EntityRepository
{
}
