<?php

namespace AppBundle\Repository;

/**
 * GuestsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GuestsRepository extends \Doctrine\ORM\EntityRepository
{
}
