app:
    resource: "@AppBundle/Controller/"
    type:     annotation

logout:
    path: /logout
    defaults: { _controller: AppBundle:Security:logout}

login:
    path: /login
    defaults: { _controller: AppBundle:Security:login}

home:
    path: /
    defaults: { _controller: AppBundle:Default:index}

user_registration:
    path: /register
    defaults: { _controller: AppBundle:Registration:register }

couple_new:
    path: /couple/new
    defaults: { _controller: AppBundle:Couple:new }

couple_edit:
    path: /couple/edit
    defaults: { _controller: AppBundle:Couple:edit }

couple_delete:
    path: /couple/delete
    defaults: { _controller: AppBundle:Couple:delete }

couple_show:
    path: /couple/show
    defaults: { _controller: AppBundle:Couple:show }

couple_index:
    path: /couple/index
    defaults: { _controller: AppBundle:Couple:index }

events_new:
    path: /events/new
    defaults: { _controller: AppBundle:Events:new }

events_edit:
    path: /events/edit
    defaults: { _controller: AppBundle:Events:edit }

events_delete:
    path: /events/delete
    defaults: { _controller: AppBundle:Events:delete }

events_show:
    path: /events/show
    defaults: { _controller: AppBundle:Events:show }

events_index:
    path: /events/index
    defaults: { _controller: AppBundle:Events:index }

guests_new:
    path: /guests/new
    defaults: { _controller: AppBundle:Guests:new }

guests_edit:
    path: /guests/edit
    defaults: { _controller: AppBundle:Guests:edit }

guests_delete:
    path: /guests/delete
    defaults: { _controller: AppBundle:Guests:delete }

guests_show:
    path: /guests/show
    defaults: { _controller: AppBundle:Guests:show }

guests_index:
    path: /guests/index
    defaults: { _controller: AppBundle:Guests:index }

items_new:
    path: /items/new
    defaults: { _controller: AppBundle:Items:new }

items_edit:
    path: /items/edit
    defaults: { _controller: AppBundle:Items:edit }

items_delete:
    path: /items/delete
    defaults: { _controller: AppBundle:Items:delete }

items_show:
    path: /items/show
    defaults: { _controller: AppBundle:Items:show }

items_index:
    path: /items/index
    defaults: { _controller: AppBundle:Items:index }

vendors_new:
    path: /vendors/new
    defaults: { _controller: AppBundle:Vendors:new }

vendors_edit:
    path: /vendors/edit
    defaults: { _controller: AppBundle:Vendors:edit }

vendors_delete:
    path: /vendors/delete
    defaults: { _controller: AppBundle:Vendors:delete }

vendors_show:
    path: /vendors/show
    defaults: { _controller: AppBundle:Vendors:show }

vendors_index:
    path: /vendors/index
    defaults: { _controller: AppBundle:Vendors:index }